train_data<-read.csv("c:/users/lenovo/documents/train.csv")
lda<-lda(train_data$Activity~.,data=train_data)
head(lda_predict)
traindata<-lda_predict[c(8:12,1)]
Library(read.csv())
library(lda)
Library(readxs)
library(readxls)
library(tidyverse)
librar(ggplot2)
library(MASS)
library(e1071)
install.packages("ggplot2", dep=T)
install.packages("tidyverse", lib="C:/Users/YourUser/Documents/R/win-library/3.3")
library(tidyverse)
install.packages("C50", lib="C:/Users/YourUser/Documents/R/win-library/3.3")
train_data<-read.csv("c:/users/lenovo/documents/train.csv")
lda<-lda(train_data$Activity~.,data=train_data)
head(lda_predict)
head(lda)
lda_predict<-as.data.frame(predict(lda,traindata))
lda_predict<-as.data.frame(predict(lda,train_data))
head(lda_predict)
traindata<-lda_predict[c(8:12,1)]
traindata<-as.data.frame(traindata)
head(traindara)
head(traindata)
testdata<-read.csv("c:/users/lenovo/documents/test.csv")
testdata<-as.data.frame(predict(lda,testdata))
testdata<-testdata[c(8:12,1)]
head(testdata)
svm_model<-svm(traindata$class~.,data=traindata)
svm_predict<-predict(svm_model,testdata
)
csvm<-caret::conjfusionMatrix(svm_predict,testdata$class)
csvm<-caret::confusionMatrix(svm_predict,testdata$class)
csvm
library(kloR)
library(klaR)
install.packages("klaR", lib="C:/Users/YourUser/Documents/R/win-library/3.3")
library(klaR)
BoxM(lda_predict[c(8:12,1)],Type)
library(heplot)
library(BoxM)
install.packages("BoxM", lib="C:/Users/YourUser/Documents/R/win-library/3.3")
BoxM(lda_predict[c(8:12,1)],Type)
install.packages("rattle", lib="C:/Users/YourUser/Documents/R/win-library/3.3")
install.packages("heplots", lib="C:/Users/YourUser/Documents/R/win-library/3.3")
library(heplots)
library(BoxM)
partimat(lda_predict[c(8)],lda_predict[c(9:10)], lda_predict$class,method="lda",main="Partitions")
nb_model<-naiveBayes(traindata,traindata$class)
nb_predict<-predict(nb_model,testdata)
cnb<-caret::confusionMatrix(nb_predict, testdata$class)
cnb
